repopath = "/Users/kOssi/lid-site/"
contentpath = "/Users/kOssi/lid-site/content/"
assetspath = "/Users/kOssi/lid-site/static/"
previewpath = "/Users/kOssi/lid-site/public/"
webfolderpath = "Users/kOssi/lid-site/www/"
#adminpath = ""